// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_RedYRVTqrO9jcqTixCgXN8ELFUy7wnY',
    appId: '1:266264966901:web:be953638d1141e434337bc',
    messagingSenderId: '266264966901',
    projectId: 'sakhrdatabase',
    authDomain: 'sakhrdatabase.firebaseapp.com',
    storageBucket: 'sakhrdatabase.firebasestorage.app',
    measurementId: 'G-1ZKSM6NPDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN_esseIs7lbAFwK9fFk_AXAdnqAl17e8',
    appId: '1:266264966901:android:f30643ca89d3dd7f4337bc',
    messagingSenderId: '266264966901',
    projectId: 'sakhrdatabase',
    storageBucket: 'sakhrdatabase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzUeXx9Q-F4ZCUD0PqtPtBOdNmqWcgHVg',
    appId: '1:266264966901:ios:730fc6cb5e43cf124337bc',
    messagingSenderId: '266264966901',
    projectId: 'sakhrdatabase',
    storageBucket: 'sakhrdatabase.firebasestorage.app',
    iosBundleId: 'com.example.appFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzUeXx9Q-F4ZCUD0PqtPtBOdNmqWcgHVg',
    appId: '1:266264966901:ios:730fc6cb5e43cf124337bc',
    messagingSenderId: '266264966901',
    projectId: 'sakhrdatabase',
    storageBucket: 'sakhrdatabase.firebasestorage.app',
    iosBundleId: 'com.example.appFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_RedYRVTqrO9jcqTixCgXN8ELFUy7wnY',
    appId: '1:266264966901:web:7c4b584025ab6cae4337bc',
    messagingSenderId: '266264966901',
    projectId: 'sakhrdatabase',
    authDomain: 'sakhrdatabase.firebaseapp.com',
    storageBucket: 'sakhrdatabase.firebasestorage.app',
    measurementId: 'G-NW93T72170',
  );
}
